#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

mysql_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  2>&1 echo 'Esperando que el servidor postgres este disponible...'
  sleep 1
done
2>&1 echo 'postgres esta disponible'

exec "$@"