version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: django_app
    depends_on:
      - postgres
    volumes:
      - ./:/app
    env_file:
      - ./.environments/dev/django/.django
      - ./.environments/dev/postgres/.postgres
    ports:
      - 8000:8000

  postgres:
    image: postgres:16.2-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.environments/dev/postgres/.postgres
    ports:
      - 5432:5432