# Generated by Django 4.2.11 on 2024-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_laboradas', models.FloatField()),
                ('tarifa_por_hora', models.FloatField()),
            ],
        ),
    ]
